{% set name = "LSSTDESC.Coord" %}
{% set version = "1.2.1" %}
{% set sha256 = "fbe8ed22222c69628def3685670b863339ce19fa5af6604e29d223cc0976d98a" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

outputs:
  - name: {{ name|lower }}
    version: {{ version }}
    build:
      script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cffi                                   # [build_platform != target_platform]
        - {{ compiler('cxx') }}
      host:
        - python
        - setuptools
        - pip
        - cffi

      run:
        - python
        - numpy
        - future
        - cffi

    test:
      files:
        - run_test.py
      imports:
        - coord
      commands:
        - {{ python }} run_test.py

  - name: {{ name|replace('.', '-')|lower }}
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("lsstdesc.coord", exact=True) }}
    test:
      files:
        - run_test.py
      imports:
        - coord
      commands:
        - {{ python }} run_test.py

about:
  home: https://github.com/LSSTDESC/Coord
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A Python module for handling angles and celestial coordinates.
  description: |
    Coord is a Python module that provides basic functionality related to angles
    and celestial coordinates. It is similar in functionality to the
    astropy.coordinates module, but with more of an emphasis on efficiency. Some
    functions are more than 100 times faster than the corresponding
    functionality in astropy. On the other hand, the API is somewhat more
    restrictive than the API used by astropy, so the appropriate module to use
    will depend on your needs.
  doc_url: https://lsstdesc.github.io/Coord/
  dev_url: https://github.com/LSSTDESC/Coord

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
